### ISSUE TITLE
@universe should be gensymed in core-state and automatically active.

### ISSUE THREAD

**Issue by mfiano** [HackerTheory/first-light#2]
This will cause the scene dsl expansion to query core-state to get the root. Then it will use that root as the parent of all nodes with no parents in the incoming dsl. THis gets rid of any explicit @universe uses and also frees the user from doing a mistake and using the name unintentionally.

Need to add a new slot in core-state and some code in make-core-instance to generate it. The actor should be stored in the :active dbs and views automatically and in the :default scene.

**Comment by psilord** [comment]
The current problem is this:

```lisp
(defun parse-scene (scene-name scene-spec)
  (with-gensyms (core-state actor-table actor-name)
    (let* ((scene-spec `((@universe ((transform)) ,@scene-spec)))
           (actor-names (%generate-actor-names scene-spec))
```

Notice how the scene-spec forces a definition of the @universe into the
scene. This is a problem because it means when loading multiple scenes,
each one gets a @universe, which is wrong.

What we need to do is automatically generate a single @universe which 
is available as an active actor in the core before any scenes get
loaded. Then, when parsing a scene, for any actors with no parents,
they automatically become a child of the single @universe.


I propose first we modify the core-state class like this:

1. Add a core-state slot called "universe-name" and set it to (gensym
"@UNIVERSE-") as the :initform. It is default :reader. We use gensym
here since we want a symbol for @universe which is of low likelihood
that it gets used when parsing scenes.



Then, inside MAKE-CORE-STATE we do these steps:

1. Create a new actor with the name created in the previous 
step and add a default transform component to it. We probably
need a real MAKE-ACTOR function instead of using make-instance
'first-light:actor. I think I had that before, but you removed it
because it "wasn't used", well now we need it back, cause we're
using it in two places (and more, since we will allow the user API
to have it).

In this specific case, we will set the state to :active for both the
actor and the component.

2. Then we insert the actor and components directly into the
actor-active-db and the component-active-view tables. This bypasses 
the initialization phase for this actor. It is ok because A) this is the
very first actor we're inserting previous to any scene being loaded,
B) It is a special case in that we know we don't need any particular
initialization for this actor.



Then, in scene.lisp's PARSE-SCENE:

1. Remove the (@universe ((transform))) addition to the scene-spec form.
We don't need this because @universe-NNN actor will always be present 
and available.

2. Get rid of add-scene-tree-root's invocation, we won't need to add a root
that is already present.

3. When you compute the scene's actor's parents, for all (NIL . XXX) 
objects, make them a child of the SCENE-TREE actor in the expansion.


Hrm, that's probably plenty, I'm sure you can fill in the rest.

**Comment by mfiano** [comment]
Fixed
