### ISSUE TITLE
core-state should use FIND-METHOD to optimize exceute-flow

### ISSUE THREAD

**Issue by mfiano** [HackerTheory/first-light#4]
When inserting an actor into core-state, core-state's API should record which protocol methods (like PHYSICS-UPDATE, UPDATE, RENDER, etc) are implemented for that component instance. Then, when mapping the fsm over the type graph, we ALSO map over a protocol view that indicates things like "Component type hit-points implements the RENDER method, so the fsm should call RENDER for that type, otherwise do not even call RENDER for that type if they didn't define one."

This prevents the method:

(defgeneric render (component) (:method (component) nil))

from being called, expensively, on components which will not have a specialized method definition for that component. Calling the above method for thousands of objects, even if it does nothing, is actually pretty expensive. We can prevent the whole lot of that from occurring.

**Comment by psilord** [comment]
wow. this markdown syntax is for children. IRC name tags with < and > are considered html tags or some such crap. Then, firefox 57 altered its plugin syntax and dropped tens of thousands of plugins, so I don't have access to vim. So now, I'm writing in a notepad window from 1995 that is dragged through an html parser. Awesome.

The future sucks.

Here is a record of the conversation:

`<psilord> like, a function that you pass a component instance too, and it returns which protocol methods it implementes.
<mfiano> hmm  [23:09]
<psilord> we still need that function even if we don't have a place to put
	  that knowledge  yet.
<mfiano> how would it know that?
<psilord> find-method
<mfiano> also the protocol methods are not clearly defined yet, especially the
	 id functions previously talked about today  [23:10]
<mfiano> so what about defun's?
<psilord> Ah the protocol methods are different than those.
<psilord> the protocol methods are specifically the ones the call flow calls.
								        [23:11]
<psilord> in the PROTOCOL-* flow-states.
<psilord> we're missing like one or two maybe, but not many.
<mfiano> it looks like what we discovered previously was not recorded in the
	 issue, and i forgot  [23:12]
<psilord> lemme look them up and stick it into the issue.
<mfiano> we needed to use another method besides find-method, and some gotchas
<psilord> unfortuantely, we didn't write it down, so we'll ahve to rediscover
	  it.
<mfiano> mfiano In other words, we have to call multiple FIND-METHODs when we
	 have multiple dispatch, because FIND-METHOD finds a very specific
	 method  [23:13]
<psilord> Ah but currently, we don't.
<psilord> currently we just need to look for a lambda list like ((component
	  hit-points) (context context))  [23:14]
<psilord> and so one, one for each define-component type.
<mfiano> sec getting log
<mfiano> mfiano If we only have this method for component QUUX: (defmethod foo
	 ((x bar) (y quux)) ..). If we are only interested in checking for the
	 component QUUX, then we have to FIND-METHOD for method (x (y quux))
	 which does not exist...only ((x bar) (y quux))  [23:15]
<psilord> that's right.  [23:16]
<psilord> and for our purposes, we're only interested in finding ((c
	  <component-type>) (context context))
<psilord> and we know all the component-types.  [23:17]
<mfiano> hCOMPUTE-APPLICABLE-METHODS  [23:18]
<mfiano> COMPUTE-APPLICABLE-METHODS
<psilord> We could make it more automatic by using a define-behavior like
	  macro instead of defmethod that can record the exact types we'll
	  need later.
<psilord> Hrm, that might work.
<mfiano> and you can't use class type T  [23:19]
<mfiano> You have to find a specific method signature
<mfiano> becuase it's not the class you're looking for here  [23:20]
<mfiano> it's a symbol representing a class
<psilord> if define-component pushnew'd the type name onto a list somewhere,
	  we can do find-method properly.  [23:21]
<psilord> that kind of special is ok, since we do not envision ever having two
	  different components of the same type loaded at different times.
<psilord> it doesn't prevent us from running multiple core-states at the same
	  time.
<psilord> If we do that, then we can know EXACTLY the method signatures to
	  look for,.  [23:22]
<mfiano> I'm not sure I agree with adding a special for book-keeping
<psilord> I think it ultimately isn't required.  [23:23]
<psilord> FIRST-LIGHT-EXAMPLE> (find-method
	  #'first-light-example::render-component '() (mapcar #'find-class
	  '(mesh-renderer context)))  [23:24]
<psilord> #<STANDARD-METHOD FIRST-LIGHT:RENDER-COMPONENT (MESH-RENDERER
	  CONTEXT) {1007FA76E3}>
<psilord> 
<psilord> do that for update-component, and you'll get a signalled condition
	  cause it isn't defined for that component.  [23:25]
<psilord> oh if :errorp is nil then it'll just return nil.  [23:26]
<mfiano> right
<psilord> god.
<psilord> good, I mean. :)
<mfiano> also you're already in the package so don't qualify :)
<psilord> well, yeah, but I was testing other stuff and left it there. :)
								        [23:27]
<mfiano> also....you don't have to call it like that
<psilord> Eh, cut and pasted from clhs. :)  [23:28]
<mfiano> it accepts a class or a class symbol
<mfiano> this would work for example: (find-method #'initialize-component nil
	 '(mesh-renderer context) nil)
<mfiano> gets rid of mapcar/find-class
<psilord> sure, but it is little difference in deciding if it works or not for
	  our purposes.  [23:29]
<psilord> Now, what we COULD do, is use compute-applicable methods for EACH
	  protocol method on an instance, then cache what we find at runtime.
<mfiano> I think everything will work, as long as we don't have multiple
	 context methods...or another argument comes along that has multiple
	 objects  [23:30]
<mfiano> compute-applicable-methods is a bit harder to use, because it takes
	 ARGUMENTS...we need actual objects to pass it for context etc
								        [23:31]
 <psilord> we could compute that in the flow.
 <psilord> when actually about to call the protocol method.
 <psilord> And we ONLY need this for the initialize-component, update-component, render-compoennt, destroy-component, and make-camera-view functions.
 <psilord> there might be one or two more we create later. All in all the subset is tiny.  [23:32]
 <psilord> we ignore all the rest of the methods on those components since those are user created or exported from gear and have a different semantic means of being called.
 <mfiano> I think FIND-METHOD is easier and requires a lot less book-keeping and references to pass around  [23:33]
 <mfiano> but maybe it's a dumb idea
 <psilord> I also agree.
 <psilord> well, why is it dumb?
 <psilord> the only interesting part is where the typename is kept for the define-component expansion.  [23:34]
 <mfiano> I guess we need to formally define all the set in stone protocol methods
 <mfiano> and see how it performs  [23:35]
 <mfiano> (and their signatures)
 <psilord> I beleive we can do that almost immediately, actually.
 <psilord> I think the only protocol method we're current missing for the components is DESTROY-COMPONENT.
 <mfiano> oh that makes sense.  [23:37]
 <psilord> yeah, but, that part of the call flow ENTRY/DESTROY-PHASE is not implemented yet. It it the part that takes actors/components marked as destroyed and removes them from core-state calling the appropriate stuff on them.
 <psilord> We'd need a first-light exported function to makr an actor or a component as destroyed.  [23:38]
 <psilord> makr->mark
 <mfiano> would they be removed from core-state or the active scene?
 <psilord> (and maybe move it to the destroyed tables in core-state, which may need to be defined.
<psilord> both.
<psilord> At the end of the frame, they would be takes out of the scene tree,
	  and out of core-state, and left to GC.  [23:39]
<psilord> Probably we'd call destroy-component on it first, so it is all legit
	  from the user's pointof view, then after that, shovel it through
	  core-state and actually remove references, etc, etc,e tc.
<mfiano> we need to hook that into mesh-renderer too  [23:40]
<psilord> mesh-renderer would implement a destroy-component and release vao
	  ids and such.
 <psilord> and that is exactly the purpose of destroy-component. :)
 <mfiano> deleting a vao when the last actor with that particular mesh-renderer vao is deleted, etc
 <psilord> Oh yeah. There might need to be a shared slot to help us out on that.  [23:41]
 <psilord> but, brb, eating some pie. :) Later.
 <mfiano> gl keeps vao's around until they are truly not used anymore
 <mfiano> only then if you try to delete it is it actually deleted from vram
 <mfiano> at least on intel/nvidia  [23:42]
 <mfiano> ok, maybe add everything we just talked about, like find-method,
	 destroy-component, vao deleting, etc to the issue. i'm too tired to
	 write it out...going to bed very shortly`

**Comment by psilord** [comment]
In short I think this'll work pretty easily actually:

```text
FIRST-LIGHT-EXAMPLE> (find-method #'initialize-component () '(mesh context))
#<STANDARD-METHOD FIRST-LIGHT:INITIALIZE-COMPONENT (MESH CONTEXT) {10081BF5D3}>
```

So all I have to do is just have a hash table keyed by type name and whose value is the set of protocol functions that type implements. Then, I know to process all components or just return immediately,
skipping all instances of that type, if they don't implement that protocol method. There might be some
odd stuff with inherited components, but meh, it'll work most of the time. :)
